# Author Information
author:
  name             : "Aditya Kumar Yadav"
  avatar           : "/images/profile.jpg"   # put your profile picture in /images/ and rename it
  bio              : "PhD student in Probability Theory. My research focuses on continuous probability distributions, developing new distributions via parsimonious methods, and exploring their applications."
  location         : "India"
  university       : "Tezpur University"   # replace with your actual university
  email            : "adityakumaryadav448@gmail.com"
  scholar          : ""  # <-- replace with your link
  github           : "akymath"   # replace with your GitHub username
  linkedin         : ""  # optional
  orcid            : ""     # optional
  twitter          : ""   # optional

# Sidebar settings
sidebar:
  nav: "docs"

# Site Settings
title              : "Aditya Kumar Yadav / Probability Theory"
description        : "Personal academic homepage of Aditya Kumar Yadav – Probability Theory, Distributions, Survival Analysis"
url                : "https://akymath.github.io"
minimal_mistakes_skin: "dark"   # options: default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
