# =============================
# Site Information
# =============================

title: "Aditya Kumar Yadav"
name: "Aditya Kumar Yadav"
email: "adityakumaryadaav448@gmail.com"
description: >
  PhD Candidate in Mathematics, specializing in Probability Theory. 
  My research focuses on continuous probability distributions, 
  parsimonious methods to generate new distributions, 
  and their mathematical properties with applications across disciplines.

baseurl: ""   # leave empty for GitHub Pages
url: "https://akymath.github.io"

# =============================
# Theme Settings
# =============================
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# Author Information
author:
  name: "Aditya Kumar Yadav"
  avatar: "/images/profile.jpg"
  location: "India"
  email: "adityakumaryadaav448@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your_email@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/akymath"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/"

# =============================
# Navigation
# =============================
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "CV"
    url: /cv.pdf
  - title: "Contact"
    url: /contact/

# =============================
# Plugins (for Jekyll & GitHub Pages)
# =============================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-remote-theme

paginate: 5
paginate_path: "/page:num/"

# =============================
# Markdown & Output
# =============================
markdown: kramdown
highlighter: rouge

# =============================
# Build Settings
# =============================
permalink: pretty
include: ["_pages"]

# =============================
# Layout Defaults
# =============================
defaults:
  # Homepage
  - scope:
      path: ""
      type: "index"
    values:
      layout: home
      author_profile: true

  # Other pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
